import type {
  ActivityEvent,
  DemoState,
  FeatureFlag,
  KycCase,
  Persona,
  Refund,
} from './types'

const at = (minutesAgo: number) =>
  new Date(Date.now() - minutesAgo * 60_000).toISOString()

const event = (
  id: string,
  actor: string,
  action: string,
  detail: string,
  minutesAgo: number,
): ActivityEvent => ({ id, actor, action, detail, at: at(minutesAgo) })

export const personas: Persona[] = [
  {
    id: 'priya',
    name: 'Priya Shah',
    initials: 'PS',
    role: 'KYC Analyst',
    team: 'Compliance',
  },
  {
    id: 'marcus',
    name: 'Marcus Reed',
    initials: 'MR',
    role: 'KYC Compliance Lead',
    team: 'Compliance',
  },
  {
    id: 'dana',
    name: 'Dana Brooks',
    initials: 'DB',
    role: 'Support Operations',
    team: 'Support',
  },
  {
    id: 'luis',
    name: 'Luis Ortega',
    initials: 'LO',
    role: 'Finance Approver',
    team: 'Finance',
  },
  {
    id: 'sam',
    name: 'Sam Chen',
    initials: 'SC',
    role: 'Platform Engineer',
    team: 'Platform',
  },
  {
    id: 'aisha',
    name: 'Aisha Khan',
    initials: 'AK',
    role: 'Release Manager',
    team: 'Platform',
  },
]

const kycCases: KycCase[] = [
  {
    id: 'KYC-2026-00123',
    customer: 'Elena Vasquez',
    email: 'elena.vasquez@example.com',
    country: 'Spain',
    type: 'Individual',
    risk: 'Critical',
    status: 'Escalated',
    assignee: 'Priya Shah',
    ageHours: 31,
    createdAt: at(1860),
    reasons: ['Potential sanctions match', 'Address mismatch'],
    documents: [
      {
        id: 'doc-123-passport',
        type: 'Passport',
        number: 'MOCK-XH49218',
        expires: '2029-08-14',
        status: 'Pending',
      },
      {
        id: 'doc-123-address',
        type: 'Proof of address',
        number: 'MOCK-UTILITY-8842',
        expires: '2027-01-01',
        status: 'Verified',
      },
    ],
    notes: ['Manual review requested after screening similarity.'],
    activity: [
      event(
        'e-123-1',
        'Screening service',
        'Risk signal added',
        '91% name similarity',
        820,
      ),
      event(
        'e-123-2',
        'Priya Shah',
        'Case escalated',
        'Lead review required',
        48,
      ),
    ],
  },
  {
    id: 'KYC-2026-00124',
    customer: 'Northstar Coffee LLC',
    email: 'ops@northstar-coffee.example.com',
    country: 'United States',
    type: 'Business',
    risk: 'High',
    status: 'In review',
    assignee: 'Priya Shah',
    ageHours: 18,
    createdAt: at(1080),
    reasons: ['Complex ownership structure'],
    documents: [
      {
        id: 'doc-124-inc',
        type: 'Certificate of incorporation',
        number: 'MOCK-DE-20491',
        expires: '2030-01-01',
        status: 'Verified',
      },
      {
        id: 'doc-124-ubo',
        type: 'Beneficial owner register',
        number: 'MOCK-UBO-311',
        expires: '2028-03-11',
        status: 'Pending',
      },
    ],
    notes: [],
    activity: [
      event(
        'e-124-1',
        'Priya Shah',
        'Review started',
        'Assigned from queue',
        92,
      ),
    ],
  },
  {
    id: 'KYC-2026-00125',
    customer: 'Daniel Okafor',
    email: 'daniel.okafor@example.com',
    country: 'Nigeria',
    type: 'Individual',
    risk: 'Medium',
    status: 'Waiting for customer',
    assignee: 'Priya Shah',
    ageHours: 54,
    createdAt: at(3240),
    reasons: ['Document image unclear'],
    documents: [
      {
        id: 'doc-125-passport',
        type: 'Passport',
        number: 'MOCK-A923771',
        expires: '2028-05-02',
        status: 'Rejected',
      },
    ],
    notes: ['Requested a clearer image of the photo page.'],
    activity: [
      event(
        'e-125-1',
        'Priya Shah',
        'Information requested',
        'Replace passport image',
        1440,
      ),
    ],
  },
  {
    id: 'KYC-2026-00126',
    customer: 'Mina Ito',
    email: 'mina.ito@example.com',
    country: 'Japan',
    type: 'Individual',
    risk: 'Low',
    status: 'New',
    assignee: 'Unassigned',
    ageHours: 2,
    createdAt: at(120),
    reasons: ['Standard onboarding'],
    documents: [
      {
        id: 'doc-126-passport',
        type: 'Passport',
        number: 'MOCK-JP11820',
        expires: '2031-11-20',
        status: 'Pending',
      },
    ],
    notes: [],
    activity: [
      event(
        'e-126-1',
        'Onboarding API',
        'Case created',
        'Standard onboarding',
        120,
      ),
    ],
  },
  {
    id: 'KYC-2026-00127',
    customer: 'Greenline Labs Ltd',
    email: 'finance@greenline-labs.example.com',
    country: 'United Kingdom',
    type: 'Business',
    risk: 'Medium',
    status: 'Approved',
    assignee: 'Marcus Reed',
    ageHours: 0,
    createdAt: at(7200),
    reasons: ['Business onboarding'],
    documents: [
      {
        id: 'doc-127-inc',
        type: 'Certificate of incorporation',
        number: 'MOCK-UK-88220',
        expires: '2030-01-01',
        status: 'Verified',
      },
    ],
    notes: ['Ownership and operating address verified.'],
    activity: [
      event(
        'e-127-1',
        'Marcus Reed',
        'Case approved',
        'All checks complete',
        4320,
      ),
    ],
  },
  {
    id: 'KYC-2026-00128',
    customer: 'Amara Diallo',
    email: 'amara.diallo@example.com',
    country: 'France',
    type: 'Individual',
    risk: 'High',
    status: 'Rejected',
    assignee: 'Marcus Reed',
    ageHours: 0,
    createdAt: at(4800),
    reasons: ['Identity could not be verified'],
    documents: [],
    notes: ['Customer did not provide requested evidence.'],
    activity: [
      event(
        'e-128-1',
        'Marcus Reed',
        'Case rejected',
        'Insufficient evidence',
        720,
      ),
    ],
  },
]

const refunds: Refund[] = [
  {
    id: 'RF-1042',
    customer: 'Elena Vasquez',
    email: 'elena.vasquez@example.com',
    paymentId: 'PAY-902184',
    amount: 249.99,
    currency: 'USD',
    reason: 'Duplicate charge',
    status: 'Failed',
    requestedBy: 'Dana Brooks',
    createdAt: at(190),
    reconciliation: 'Discrepancy',
    attempts: 1,
    notes: ['Processor timeout after authorization reversal.'],
    activity: [
      event(
        'rf-1042-1',
        'Payment processor',
        'Refund failed',
        'Temporary processor error',
        175,
      ),
    ],
  },
  {
    id: 'RF-1043',
    customer: 'Mina Ito',
    email: 'mina.ito@example.com',
    paymentId: 'PAY-902207',
    amount: 89,
    currency: 'USD',
    reason: 'Service not received',
    status: 'Pending approval',
    requestedBy: 'Dana Brooks',
    createdAt: at(88),
    reconciliation: 'Pending',
    attempts: 0,
    notes: [],
    activity: [
      event(
        'rf-1043-1',
        'Dana Brooks',
        'Refund submitted',
        'Awaiting checker approval',
        88,
      ),
    ],
  },
  {
    id: 'RF-1044',
    customer: 'Northstar Coffee LLC',
    email: 'ops@northstar-coffee.example.com',
    paymentId: 'PAY-901122',
    amount: 1240,
    currency: 'USD',
    reason: 'Billing adjustment',
    status: 'Pending approval',
    requestedBy: 'Dana Brooks',
    createdAt: at(420),
    reconciliation: 'Pending',
    attempts: 0,
    notes: ['High-value refund requires finance approval.'],
    activity: [
      event(
        'rf-1044-1',
        'Dana Brooks',
        'Refund submitted',
        'High-value review required',
        420,
      ),
    ],
  },
  {
    id: 'RF-1045',
    customer: 'Daniel Okafor',
    email: 'daniel.okafor@example.com',
    paymentId: 'PAY-899102',
    amount: 39.5,
    currency: 'USD',
    reason: 'Goodwill credit',
    status: 'Succeeded',
    requestedBy: 'Dana Brooks',
    createdAt: at(2500),
    reconciliation: 'Matched',
    attempts: 1,
    notes: [],
    activity: [
      event(
        'rf-1045-1',
        'Payment processor',
        'Refund succeeded',
        'Processor reference MOCK-7712',
        2410,
      ),
    ],
  },
  {
    id: 'RF-1046',
    customer: 'Greenline Labs Ltd',
    email: 'finance@greenline-labs.example.com',
    paymentId: 'PAY-900114',
    amount: 480,
    currency: 'USD',
    reason: 'Subscription cancellation',
    status: 'Rejected',
    requestedBy: 'Dana Brooks',
    createdAt: at(900),
    reconciliation: 'Matched',
    attempts: 0,
    notes: ['Refund outside contractual window.'],
    activity: [
      event(
        'rf-1046-1',
        'Luis Ortega',
        'Refund rejected',
        'Outside policy window',
        810,
      ),
    ],
  },
  {
    id: 'RF-1047',
    customer: 'Amara Diallo',
    email: 'amara.diallo@example.com',
    paymentId: 'PAY-902441',
    amount: 129,
    currency: 'USD',
    reason: 'Duplicate charge',
    status: 'Processing',
    requestedBy: 'Dana Brooks',
    createdAt: at(25),
    reconciliation: 'Pending',
    attempts: 1,
    notes: [],
    activity: [
      event(
        'rf-1047-1',
        'Luis Ortega',
        'Refund approved',
        'Sent to processor',
        12,
      ),
    ],
  },
]

const flags: FeatureFlag[] = [
  {
    key: 'checkout-v2',
    name: 'Checkout v2',
    description: 'New streamlined checkout experience.',
    owner: 'Payments Platform',
    tags: ['checkout', 'customer-facing'],
    protected: true,
    archived: false,
    killed: false,
    pendingChange: null,
    environments: {
      development: { enabled: true, rollout: 100 },
      staging: { enabled: true, rollout: 100 },
      production: { enabled: true, rollout: 25 },
    },
    activity: [
      event(
        'flag-1',
        'Aisha Khan',
        'Production rollout changed',
        '10% → 25%',
        380,
      ),
    ],
  },
  {
    key: 'instant-refunds',
    name: 'Instant refunds',
    description: 'Routes eligible refunds through the instant path.',
    owner: 'Money Movement',
    tags: ['refunds', 'operations'],
    protected: true,
    archived: false,
    killed: false,
    pendingChange: {
      environment: 'production',
      enabled: true,
      requestedBy: 'Sam Chen',
    },
    environments: {
      development: { enabled: true, rollout: 100 },
      staging: { enabled: true, rollout: 100 },
      production: { enabled: false, rollout: 0 },
    },
    activity: [
      event(
        'flag-2',
        'Sam Chen',
        'Change requested',
        'Enable in production',
        45,
      ),
    ],
  },
  {
    key: 'kyc-risk-model-v3',
    name: 'KYC risk model v3',
    description: 'Uses the latest risk scoring model for new cases.',
    owner: 'Compliance Engineering',
    tags: ['kyc', 'risk'],
    protected: true,
    archived: false,
    killed: true,
    pendingChange: null,
    environments: {
      development: { enabled: true, rollout: 100 },
      staging: { enabled: true, rollout: 100 },
      production: { enabled: false, rollout: 0 },
    },
    activity: [
      event(
        'flag-3',
        'Aisha Khan',
        'Kill switch activated',
        'Elevated false positives',
        92,
      ),
    ],
  },
  {
    key: 'support-console-search',
    name: 'Support console search',
    description: 'Unified customer and transaction search.',
    owner: 'Support Systems',
    tags: ['support', 'search'],
    protected: false,
    archived: false,
    killed: false,
    pendingChange: null,
    environments: {
      development: { enabled: true, rollout: 100 },
      staging: { enabled: true, rollout: 100 },
      production: { enabled: true, rollout: 100 },
    },
    activity: [event('flag-4', 'Sam Chen', 'Flag enabled', 'Production', 1300)],
  },
  {
    key: 'legacy-kyc-export',
    name: 'Legacy KYC export',
    description: 'Previous nightly KYC export workflow.',
    owner: 'Compliance Engineering',
    tags: ['kyc', 'legacy'],
    protected: false,
    archived: true,
    killed: false,
    pendingChange: null,
    environments: {
      development: { enabled: false, rollout: 0 },
      staging: { enabled: false, rollout: 0 },
      production: { enabled: false, rollout: 0 },
    },
    activity: [
      event(
        'flag-5',
        'Aisha Khan',
        'Flag archived',
        'Migration completed',
        8400,
      ),
    ],
  },
]

export const createInitialState = (): DemoState => ({
  personas,
  personaId: 'priya',
  theme: 'light',
  kycCases,
  refunds,
  flags,
  notices: [],
  lastUpdated: new Date().toISOString(),
})
